### ISSUE TITLE
AND BROKEN UNTIL THE OFFICIAL RELEASE.

### ISSUE THREAD

**Issue by KARLA0619** [ParallelProductions/SpongeBob-Obstacle-Odyssey-3#1]
https://github.com/ParallelProductions/SpongeBob-Obstacle-Odyssey-3/blob/1beb3acb8166f7ded92afe50cfff42562c858cbd/README.md#L6

**Comment by ParallelProductions** [comment]
Buggy And Broken But Playable. Download and play it yourself :)
